{% set name = "linkchecker" %}
{% set version = "10.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LinkChecker-{{ version }}.tar.gz
  sha256: 97eae069ccfe892a18e380c7f4762dfe3f352e87c442ef6124e8c60b887cddcd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - linkchecker = linkcheck.command.linkchecker:linkchecker

requirements:
  host:
    - python >=3.7
    - pip
    # Linkchecker uses hatchling and the hatch-vcs plugin to build
    - hatchling
    - hatch-vcs
  run:
    - python >=3.7
    - beautifulsoup4 >=4.8.1
    - dnspython >=2.0
    - requests >=2.4

test:
  imports:
    - linkcheck
  commands:
    - pip check
    - linkchecker --version
  requires:
    - pip

about:
  home: https://linkchecker.github.io/linkchecker/
  summary: Check websites for broken links
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - saraedum
